[package]
name = "viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[toolchain]
channel = "nightly"

[workspace]

[dependencies]
debug_print = "1.0.0"
math_lib_3d = { path = "../math_lib_3d" }

